#! /bin/bash
#
# Start mongod
local=$PWD

echo "Start mongo with local logging if not already running"
if [ $(pgrep -f mongod) ]
then
  echo "mongod is already running"
else
  echo "mongod not running, starting it up"
  echo "(you will have to enter sudo password)..."
  #Delete prior mongodb log(s)
  sudo rm ./log/mongod.log*
  sudo mongod --fork --dbpath /var/lib/mongodb --logpath ./log/mongod.log
  echo "waiting 5 seconds for mongod to start..."
  sleep 5
fi

echo "(re)start local instance of redis-server if not already running..."
if [ $(pgrep -f redis-server.*6380) ]
then
  echo "stopping redis-server on port 6380..."
  kill $(pgrep -f redis-server.*6380)
fi
echo "Starting new instance of redis-server on port 6380"
#Delete prior redis console log(s)
rm ./log/redis-console.log*
redis-server ./config/redis-fh.conf > ./log/redis-console.log &
echo "waiting 5 seconds for redis-server to start..."
sleep 5

echo "starting application..."
rails server --binding 127.0.0.1



