development:
  host: localhost
  thread_safe: true
  port: 6379
  db: 11
  
test:
  host: localhost
  thread_safe: true
  port: 6379
  db: 2

production:
  host: localhost
  thread_safe: true
  port: 6379
